### ISSUE TITLE
Default colour is invalid

### ISSUE THREAD

**Issue by Simetraa** [untitled-team-101/Whiteboard#10]
The default shape pen colour is not in the correct format, so it draws with (I assume, a default of green). 
`drawShapes.js:184 The specified value "black" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
(anonymous) @ drawShapes.js:184`

![image](https://user-images.githubusercontent.com/67224309/135760360-0c203877-9784-4dd5-b45b-265666a0170f.png)

**Comment by sabderemane** [comment]
Hi @Simetraa, can I be assign to this issue ?

**Comment by dhruvgarg02** [comment]
@Simetraa As you have opened the issue, Would you like the Issue to be assigned to you?

**Comment by Simetraa** [comment]
> @Simetraa As you have opened the issue, Would you like the Issue to be assigned to you?

Sure, I've almost fixed it.
