### ISSUE TITLE
Need pop-up(modal) for saving/downloading file with user-defined names

### ISSUE THREAD

**Issue by tanmayVaish** [untitled-team-101/Whiteboard#14]
Right now, when you download the board, it is saved with "**untitled.png**" . 

Now, what we need is to get a pop-up dialog box with a input field, there you can type the name of the file (For ex. hacktoberfest.png). 

There will also be a default value for input field, (for ex. board_<_time-stamp_>).

**Comment by suprabhat25** [comment]
Can you assign this issue to me ?

**Comment by tanmayVaish** [comment]
@suprabhat25 yeah cool, you are assigned this issue. Godspeed!

**Comment by Aswal-Ashutosh** [comment]
> Right now, when you download the board, it is saved with "**untitled.png**" .
> 
> Now, what we need is to get a pop-up dialog box with a input field, there you can type the name of the file (For ex. hacktoberfest.png).
> 
> There will also be a default value for input field, (for ex. board_<_time-stamp_>).

@tanmayVaish Assign it to me.
