### ISSUE TITLE
Add Background color to save images

### ISSUE THREAD

**Issue by grawish** [untitled-team-101/Whiteboard#15]
# Background color
When you download the board as an image you do not get background otherwise, you get transparent strokes only.
### Actual image
![Screenshot from 2021-10-04 00-38-31](https://user-images.githubusercontent.com/41504211/135768017-31f20a27-0a9e-4680-9902-808c9b8d2b16.png)

### Downloaded image
![Screenshot from 2021-10-04 00-38-47](https://user-images.githubusercontent.com/41504211/135768024-b0333838-1c1e-4e2d-9e1c-3d520b7ef7c1.png)

**Comment by vczoika** [comment]
May I work on this issue? I think I found a way to adjust that

**Comment by MuhammadTanveer94** [comment]
@grawish can i work on this?

**Comment by tanmayVaish** [comment]
@vczoika Done, I have assigned you with this issue! Send us a PR soon!! Good Luck!
