### ISSUE TITLE
Shape drawing is sometimes duplicated

### ISSUE THREAD

**Issue by Sundava** [untitled-team-101/Whiteboard#23]
When rapidly drawing shapes (Line, square, circle, not seen with triangle), more than one shape is sometimes drawn for a single mouseup event.

Example:
![Screenshot from 2021-10-04 15-53-12](https://user-images.githubusercontent.com/7022870/135864291-05379a1e-a0ec-4288-b523-0c6dc5c9a1f3.png)

This ripple is made from a single click & drag

**Comment by tanmayVaish** [comment]
@Sundava Cool, You can work on this one! Send a PR, Good luck
