### ISSUE TITLE
Pen is unable to draw dots. 

### ISSUE THREAD

**Issue by tanmayVaish** [untitled-team-101/Whiteboard#8]
Our pen and markers are unable to make dots, We have to **at least _hold and drag_** it to make drawings.

**Comment by nikhil9302** [comment]
hey!, i can try to work on this issue. Do assign it to me.

**Comment by RaviTejaVattem** [comment]
I want to give a try here.

To my understanding the expectation is currently we are unable to create a dot without mousedrag which should be enabled

I think I need to check Whiteboard\scripts\pencilBox.js

Please let me know if my understanding is correct

**Comment by tanmayVaish** [comment]
Yes you are right! @RaviTejaVattem I have assigned you with this issue!! Send us a PR.
